### ISSUE TITLE
Number of nodes

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/eureka#1]
### Tasks
- [x] Determine the total number of nodes for the new cluster

### Notes
- Include both login and computing nodes
- Take into account the EthernetIB switches, power strips, and 360mm water cooler
- IO ports should be at the front of the case
- Be careful about the height of PSU, GPU ([Nvidia RTX 3080 dimension](https://www.techpowerup.com/gpu-specs/geforce-rtx-3080.c3621)), and water cooler
- @xuanweishan suggests 29 nodes (and 32 nodes at most if we put three nodes on the top of rack)
- @koarakawaii: 42U rack inner height is about 1867 mm, and the height of 4U case is 177 mm, so 1 rack can accommodate 10 cases.

**Comment by hyschive** [comment]
@xuanweishan @koarakawaii Have you reached an agreement on this?

**Comment by koarakawaii** [comment]
@hyschive I agree with @xuanweishan 's calculation (29 nodes). 1U of 1 rack will be occupied by InfiniBand switch and router, so total `10 node_per_rack*3 rack - 1 node = 29 nodes`.
