### ISSUE TITLE
GPU  tilted due to overweight

### ISSUE THREAD

**Issue by koarakawaii** [calab-ntu/eureka#10]
# Log
[2021/07/08] GPU on `Eureka 12` is found to be tilted and error happened:
```
Unable to determine the device handle for GPU 0000:41:00.0: Unknown Error
```
![](https://drive.google.com/uc?export=view&id=1Ux_3_uqA-weAFLPz_MPuh3PP1nPuMMBT)

[2021/07/08] GPU is about 5 cm longer than MB.
![](http://drive.google.com/uc?export=view&id=1l_iDGKD6iPAa7GPNk54Qm3PA-YJLmL_C)

[2021/07/14] GPU is supported by the newly brought product (Solution 1)
![](http://drive.google.com/uc?export=view&id=1Zp6w2ic67dh4QDmmM7cXCi1frf2S-qVZ)
![](http://drive.google.com/uc?export=view&id=1WLsGusJvFJMS9MdyeY0Dia7UJQAJRKNw)
```
The support is not higher than GPU so we don't have to worried about the height.
And the bottom is flat that it won't occupy space for other component.
Seems good.
Comment by Wei-Hsuan
```

[2021/07/19] Cover metal base and support arm with electric tape to prevent isolate electric between GPU and PSU. 
![](http://drive.google.com/uc?export=view&id=1DOJB7UdQleAWvmGWFT0N5Rm2hjyw26ur)
Apply GPU support on `eureka12` for test. 
![](http://drive.google.com/uc?export=view&id=16REZzLWeCobwg_0MVGBfZvotbzLsNXGg)
![](http://drive.google.com/uc?export=view&id=1LlbB5qaMe1m1g9n8R4N1TFJmkTpBpLEg)

[2021/07/20]  `nvidia-smi` report error 
```
Unable to determine the device handle for GPU 0000:41:00.0: Unknown Error
```
and error report messages are found in `/var/log/messages` in `eureka12`
```
kernel: NVRM: GPU at PCI:0000:41:00: GPU-c81a0b0a-4162-ac65-bb8b-bf05993f66d8
kernel: NVRM: GPU Board Serial Number:
kernel: NVRM: Xid (PCI:0000:41:00): 79, pid=0, GPU has fallen off the bus.
kernel: NVRM: GPU 0000:41:00.0: GPU has fallen off the bus.
kernel: NVRM: GPU 0000:41:00.0: GPU is on Board .
kernel: NVRM: A GPU crash dump has been created. If possible, please run#012NVRM: nvidia-bug-report.sh as root to collect this data before#012NVRM: the NVIDIA kernel module is unloaded.
```

# Solution
1. Buy [this](https://24h.pchome.com.tw/prod/DRAE6X-A900B1C93?gclid=CjwKCAjw55-HBhAHEiwARMCszonvElapbQxow1o60CXpiM4BMO2FbE8wGrmxGFjuzgu95OO0S_VNhhoCOSIQAvD_BwE)
2. DIY support

**Comment by xuanweishan** [comment]
The process of installing GPU support:
1. Cover GPU support with electro-tape 
1. Confirm computer is powered off.
2. Uninstall GPU
3. Lift up PSU.
4. Put GPU support between MB and PSU.
5. Put down PSU.
6. Install GPU and adjust the height of support
7. Check. 
   - [ ] GPU support is stable.
   - [ ] Fans on GPU won't be effect by the support.
   - [ ] Power cables are connect properly.
