### ISSUE TITLE
Add GPU temperature threshold

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/eureka#14]
Add a GPU temperature threshold to the figure `GPU_avereage_temperature_in_7_days` in the Eureka weekly summary

**Comment by xuanweishan** [comment]
Done.
Threshold in figure of GPU average temperature in 7 days is added.
![image](https://user-images.githubusercontent.com/30583700/126133507-fbe8fe7b-b5db-4d11-871d-2e8f2519a336.png)
