### ISSUE TITLE
RAM test

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/eureka#2]

**Comment by xuanweishan** [comment]
RAM test progress
- [x] `00` [2021/09/08] All RAMs on `eureka00` passed RAM test.
- [x] `01` [2021/08/13] Failed w/ 1 error. [2021/08/16] Passed.
- [x] `02` [2021/08/16] Passed.
- [x] `03` [2021/08/16] Passed.
- [x] `04` [2021/06/25] Passed.
- [x] `05` [2021/06/15] Passed.
- [x] `06` [2021/06/25] Failed. [2021/06/30] Passed.
- [x] `07` [2021/07/05] Failed. [2021/07/16] Passed.
- [x] `08` [2021/07/02] Failed. [2021/07/05] Failed. [2021/07/14] Failed w/ 44 errors. [2021/07/16] Passed.
- [x] `09` [2021/06/28] Passed.
- [x] `10` [2021/07/26] Passed.
- [x] `11` [2021/08/06] Failed w/ 10196 errors. [2021/08/17] Failed w/ 26 errors [2021/08/20] Failed w/ 16 errors. [2021/08/27] Passed.
- [x] `12` [2021/07/02] Failed. [2021/07/07] Passed
- [x] `13` [2021/07/07] Failed. [2021/07/09] Failed w/ 1 error. [2021/01/12] Failed w/ 4 errors. [2021/07/14] Failed w/ 40 errors. [2021/08/18] Passed.
- [x] `14` [2021/07/23] Passed.
- [x] `15` [2021/07/12] Passed.
- [x] `16` [2021/06/21] Passed.
- [x] `17` [2021/06/17] Passed.
- [x] `18` [2021/07/23] Fail w/ 10008 errors. [2021/07/27] Passed.
- [x] `19` [2021/07/28] Passed.
- [x] `20` [2021/08/03] Passed.
- [x] `21` [2021/07/21] Passed.
- [x] `22` [2021/08/05] Passed.
- [x] `23` [2021/08/02] Failed w/ 136 errors. [2021/08/06] Passed.
- [x] `24` [2021/06/17] Failed. [2021/06/21] Passed.
- [x] `25` [2021/06/21] Passed.
- [x] `26` [2021/06/23] Failed. [2021/06/25] Failed. [2021/07/02] Passed.
- [x] `27` [2021/08/06] Passed.
- [x] `28` [2021/07/29] Passed.
- [x] `29` [2021/06/23] Passed.
- [x] `30` [2021/06/23] Passed.
- [x] `31` [2021/06/17] Passed.
- [x] `32` [2021/06/11] Passed.
- [x] `33` [2021/07/28] Passed.

**Comment by xuanweishan** [comment]
Number of broken RAMs: 11 pairs.
- [x] Replace broken RAMs.
  > 8 pairs of RAMs are returned and claimed as normal.
  > After test by using RAMtest86, 5 pairs still reprot. Error numbers are between 1 to 20.
  > Kingston said that is normal as non ecc D-RAM.

New broken RAMs founded: 1 pairs.
- [x] Replace broken RAMs.
  > [2021/09/15] The last pair of broken RAM is sent to Kingston.
