### ISSUE TITLE
Bash history timestamp

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/eureka#26]
### Goals
Record the bash history timestamp (date and time) on all nodes.

**Comment by xuanweishan** [comment]
By edit the file `/etc/profile`
Adding the line `export HISTTIMEFORMAT='%d/%m/%y %T '` at the end of file.
And execute command `source /etc/profile`
![image](https://user-images.githubusercontent.com/30583700/130718906-0f5fad88-a0e6-4859-858f-b769053d6fa3.png)
