### ISSUE TITLE
Purchase a 10G ethernet switch.

### ISSUE THREAD

**Issue by xuanweishan** [calab-ntu/eureka#43]
Specifications.
1. Supply both 110V and 220V power
2. Having more than 30 10G RJ45 port.
3. Cann't be a chinese company made product.

**Comment by xuanweishan** [comment]
opitons:
1. NETGEAR XS748T : 202,125 NTD
    ref. https://www.netgearstore.com.tw/products/xs748t
2. D-link DXS-3400 : 229,199 NTD 
    ref. https://www.dlinktw.com.tw/business/product?id=980&hid=1
    price: https://www.ruten.com.tw/item/show?21623835073864

I thought the second one is the best choise now.

**Comment by xuanweishan** [comment]
I prefer Netgear XS748T.
'Cause it support 10G network RJ45 ports, so that we don't need to buy adapters for each ports. 
And it has enough ports for our all nodes that we don't have to buy more than 2.

**Comment by hyschive** [comment]
@xuanweishan Agree. Proceed.
