### ISSUE TITLE
Purchase a new switch (1G or 2.5G) with 48 port.

### ISSUE THREAD

**Issue by xuanweishan** [calab-ntu/eureka#44]
specification : 
1. support 1G or 2.5G ethernet.
2. has 48 ports or more.

**Comment by xuanweishan** [comment]
#### 2.5G: Can not find a 2.5G switch with more than 48 ports.

#### 1G :
zyxel
1. GS1920-48v2: https://www.zyxel.com/tw/zh/products/switch/8-24-48-port-gbe-smart-managed-switch-gs1920-series/specification
    price: 21000 NTD https://www.genb2b.com/prohtml/4fc/4fe25c6e.html?
2. GS1900-48: https://www.zyxel.com/tw/zh/products/switch/8-10-16-24-48-port-gbe-smart-managed-switch-gs1900-series/specification
    price: 14050 NTD https://24h.pchome.com.tw/prod/DRAF0I-A900D67ME
3. XGS1930-52: https://www.zyxel.com/tw/zh/products/switch/24-48-port-gbe-lite-l3-smart-managed-switch-with-4-10g-uplink-xgs1930-series/specifications
    price: 42500 NTD https://tw.mall.yahoo.com/item/%E2%97%A4%E5%85%A8%E6%96%B0%E5%93%81-%E5%90%AB%E7%A8%85-%E5%85%8D%E9%81%8B%E8%B2%BB%E2%97%A2-ZyXEL-XGS1930-52-%E6%99%BA%E6%85%A7%E5%9E%8B%E7%B6%B2%E7%AE%A1-p0110222497855?_co=pfeeW_150701_01_PGAC_ggvIAACQZ0SjEGOEIA%3D%3D.9f
4. XGS2210-52: https://www.zyxel.com/tw/zh/products/switch/24-48-port-gbe-layer-3-access-switch-with-10gbe-uplink-xgs2210-series/specification
    price: 75600 NTD https://www.pcstore.com.tw/point/M24268642.htm
5. GS2220-50 https://www.zyxel.com/tw/zh/products/switch/10-28-50-port-gbe-l2-managed-switch-gs2220-series/specifications
    price: 33500 NTD https://www.genb2b.com/prohtml/00c/000dca19.html?

netgear
1. GS348 https://www.netgearstore.com.tw/products/gs348
    price: 11550 NTD

D-link
1. DGS-1250-52X https://www.dlinktw.com.tw/business/product?id=2072&hid=1
    price: 26250 NTD https://www.teksource.com.tw/products-detail/52%E5%9F%A0L2-Smart-Switch-*%E5%A4%A7%E7%BC%BA-i.61429
2. DGS-1210-52 https://www.dlinktw.com.tw/business/product?id=353&hid=1
    price: 13678 NTD https://24h.pchome.com.tw/prod/DSBA1P-A900AMNYP?gclid=Cj0KCQiA14WdBhD8ARIsANao07jiD1FUcnQjeYABhzAFv1N1R39JgCV6uggeMQu6-AKTqTMJgtriIy4aAgjcEALw_wcB
3. DGS-1510-52X https://www.dlinktw.com.tw/business/product?id=898&hid=1
    price: 34750 NTD https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=7778532&osm=richbuy&utm_source=CPA&utm_medium=feebee-1_PLwQExAvIAACQHIfzEGNEfQ%253D%253D.99
4. DGS-3130-54TS https://www.dlinktw.com.tw/business/product?id=1042&hid=1
    price: 66420 NTD https://www.pcstore.com.tw/3c91/M54915160.htm
5. DGS-3120-48TC https://www.dlinktw.com.tw/business/product?id=378&hid=1
    price: 40570 NTD https://www.pcstore.com.tw/3c91/M13797683.htm

**Comment by xuanweishan** [comment]
### Specification comparison
| Product | price | #1G ports | #sfp ports | 背板頻寬(Gbps) | 交換轉送率(Mpps) | 封包緩衝區(byte) | 保固 |
|:---------|------:|:------------|:------------|:------------------|:----------------------|:---------------------|:------|
|GS1548(current using)|----|48|4(1G)|96|71|512K| ---| 
|GS1920-48v2|21000|48|2(1G)|100|74|1.5M|3 years|
|GS1900-48|14050|48|2(1G)|100|74|525K|3 years|
|XGS1930-52|42500|48|4(10G)|176|130|1.5M|3 years|
|XGS2210-52|75600|48|4(10G)|176|130|1.5M|3 years|
|GS2220-50|75600|48|2(1G)|100|74|1.5M|3 years|
|GS348|11550|48|0|96|1448000pps|1.5M|3 years|
|DGS-1250-52X|26250|48|4(10G)|176|130|1.5M|3 years|
|DGS-1210-52|13678|48(52)|4(1G)|104|77|1.5M|3 years|
|DGS-1510-52X|34750|48|4(10G)|176|130|3M|3 years|
|DGS-3130-54TS|66420|48(1G)+2(10G)|4(10G)|216|161|4M|3 years|
|DGS-3120-48TC|40570|44(48)|4(1G)|136|101|2M|3 years|

**Comment by xuanweishan** [comment]
For 1G switch, I recomend D-link DGS-1250-52 or DGS-1250-52X. 
Because they are cheaper than similar product but with stronger spec.

**Comment by hyschive** [comment]
@xuanweishan Do you think that we can take advantage of the 4(10G) ports in DGS-1250-52X to connect to NAS?

**Comment by xuanweishan** [comment]
To increase the bandwidth of NAS buy the fsp+ adaptor from synology.

**Comment by xuanweishan** [comment]
The IP of the switch is set to 192.168.0.50
